chore: update various configuration files and improve code structure; enhance type definitions and clean up formatting across multiple components and services

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,128 +1,128 @@
 stages:
-    - build
-    - release
+  - build
+  - release
 
 cache:
-    paths:
-        - node_modules/
+  paths:
+    - node_modules/
 
 build_packagedev_mac:
-    image: node
-    stage: build
-    tags:
-        - arm64
-    only:
-        - tags
-    variables:
-        ELECTRON_BUILDER_CACHE: '${CI_PROJECT_DIR}/.cache/electron-builder'
-        CERTIFICATE_PASSWORD: '${CERTIFICATE_PASSWORD}'
-    before_script:
-        - apt-get update
-        - apt-get install -y libx11-dev libxkbfile-dev libsecret-1-dev
-        - dpkg --add-architecture arm64
-        - apt-get update
-        - apt-get install -y wine64
-        - echo "$CERTIFICATE_BASE64" | base64 -d > certificate.pfx
+  image: node
+  stage: build
+  tags:
+    - arm64
+  only:
+    - tags
+  variables:
+    ELECTRON_BUILDER_CACHE: '${CI_PROJECT_DIR}/.cache/electron-builder'
+    CERTIFICATE_PASSWORD: '${CERTIFICATE_PASSWORD}'
+  before_script:
+    - apt-get update
+    - apt-get install -y libx11-dev libxkbfile-dev libsecret-1-dev
+    - dpkg --add-architecture arm64
+    - apt-get update
+    - apt-get install -y wine64
+    - echo "$CERTIFICATE_BASE64" | base64 -d > certificate.pfx
 
-    script:
-        - export CERTIFICATE_PASSWORD=${CERTIFICATE_PASSWORD}
-        - sed -i "s/__CERT_PASS__/${CERTIFICATE_PASSWORD}/g" package.json
-        - yarn install --frozen-lockfile --ignore-engines
-        - yarn release:mac
-    artifacts:
-        paths:
-            - dist/
-        expire_in: 4 weeks
-    cache:
-        paths:
-            - .cache/electron-builder
-            - node_modules/
+  script:
+    - export CERTIFICATE_PASSWORD=${CERTIFICATE_PASSWORD}
+    - sed -i "s/__CERT_PASS__/${CERTIFICATE_PASSWORD}/g" package.json
+    - yarn install --frozen-lockfile --ignore-engines
+    - yarn release:mac
+  artifacts:
+    paths:
+      - dist/
+    expire_in: 4 weeks
+  cache:
+    paths:
+      - .cache/electron-builder
+      - node_modules/
 
 build_packagedev:
-    image: node
-    stage: build
-    only:
-        - tags
-    variables:
-        ELECTRON_BUILDER_CACHE: '${CI_PROJECT_DIR}/.cache/electron-builder'
-        # Make sure the variable is available in the script environment
-        CERTIFICATE_PASSWORD: '${CERTIFICATE_PASSWORD}'
-    before_script:
-        - apt-get update
-        - apt-get install -y libx11-dev libxkbfile-dev libsecret-1-dev
-        - dpkg --add-architecture i386
-        - apt-get update
-        - apt-get install -y wine64 wine32
-        - wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
-        - dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb
+  image: node
+  stage: build
+  only:
+    - tags
+  variables:
+    ELECTRON_BUILDER_CACHE: '${CI_PROJECT_DIR}/.cache/electron-builder'
+    # Make sure the variable is available in the script environment
+    CERTIFICATE_PASSWORD: '${CERTIFICATE_PASSWORD}'
+  before_script:
+    - apt-get update
+    - apt-get install -y libx11-dev libxkbfile-dev libsecret-1-dev
+    - dpkg --add-architecture i386
+    - apt-get update
+    - apt-get install -y wine64 wine32
+    - wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
+    - dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb
 
-        # Download the certificate file from GitLab repository
-        #- >
-        #curl -L --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}"
-        #-o certificate.pfx
-        #"https://git.nosi.cv/api/v4/projects/${CI_PROJECT_ID}/repository/files/certificate%2Fcertificate.pfx/raw?ref=master"
+    # Download the certificate file from GitLab repository
+    #- >
+    #curl -L --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}"
+    #-o certificate.pfx
+    #"https://git.nosi.cv/api/v4/projects/${CI_PROJECT_ID}/repository/files/certificate%2Fcertificate.pfx/raw?ref=master"
 
-        - echo "$CERTIFICATE_BASE64" | base64 -d > certificate.pfx
+    - echo "$CERTIFICATE_BASE64" | base64 -d > certificate.pfx
 
-    script:
-        - export CERTIFICATE_PASSWORD=${CERTIFICATE_PASSWORD}
-        - sed -i "s/__CERT_PASS__/${CERTIFICATE_PASSWORD}/g" package.json
-        - yarn install --frozen-lockfile --ignore-engines
-        - yarn release:win
-        - yarn release:linux
-        #- yarn release:mac
-    artifacts:
-        paths:
-            - dist/
-        expire_in: 4 weeks
-    cache:
-        paths:
-            - .cache/electron-builder
-            - node_modules/
+  script:
+    - export CERTIFICATE_PASSWORD=${CERTIFICATE_PASSWORD}
+    - sed -i "s/__CERT_PASS__/${CERTIFICATE_PASSWORD}/g" package.json
+    - yarn install --frozen-lockfile --ignore-engines
+    - yarn release:win
+    - yarn release:linux
+    #- yarn release:mac
+  artifacts:
+    paths:
+      - dist/
+    expire_in: 4 weeks
+  cache:
+    paths:
+      - .cache/electron-builder
+      - node_modules/
 
 release:
-    stage: release
-    only:
-        - tags
-    image: curlimages/curl:latest
-    script:
-        - echo "Uploading artifacts to GitLab release..."
-        - |
-            for file in dist/*; do
-              filename=$(basename "$file" | sed 's/ /%20/g')
-              echo "Uploading $file..."
-              UPLOAD_URL="https://git.nosi.cv/api/v4/projects/${CI_PROJECT_ID}/packages/generic/electron-builder/${CI_COMMIT_TAG}/$(basename "$file")"
-              echo "Upload URL: $UPLOAD_URL"
-              
-              if [[ -n "${GITLAB_TOKEN}" && -n "${CI_PROJECT_ID}" && -n "${CI_COMMIT_TAG}" ]]; then
-                curl --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
-                     --upload-file "$file" \
-                     "$UPLOAD_URL"
-              else
-                echo "Error: Missing required environment variables."
-                exit 1
-              fi
-            done
+  stage: release
+  only:
+    - tags
+  image: curlimages/curl:latest
+  script:
+    - echo "Uploading artifacts to GitLab release..."
+    - |
+      for file in dist/*; do
+        filename=$(basename "$file" | sed 's/ /%20/g')
+        echo "Uploading $file..."
+        UPLOAD_URL="https://git.nosi.cv/api/v4/projects/${CI_PROJECT_ID}/packages/generic/electron-builder/${CI_COMMIT_TAG}/$(basename "$file")"
+        echo "Upload URL: $UPLOAD_URL"
+        
+        if [[ -n "${GITLAB_TOKEN}" && -n "${CI_PROJECT_ID}" && -n "${CI_COMMIT_TAG}" ]]; then
+          curl --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
+               --upload-file "$file" \
+               "$UPLOAD_URL"
+        else
+          echo "Error: Missing required environment variables."
+          exit 1
+        fi
+      done
 
-        - echo "Creating a new release on GitLab..."
-        - |
-            curl --request POST \
-                 --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
-                 --header "Content-Type: application/json" \
-                 --data "{
-                   \"name\": \"Release ${CI_COMMIT_TAG}\",
-                   \"tag_name\": \"${CI_COMMIT_TAG}\",
-                   \"description\": \"Release for commit ${CI_COMMIT_SHA}\",
-                   \"assets\": {
-                     \"links\": [
-                       {
-                         \"name\": \"Download\",
-                         \"url\": \"https://git.nosi.cv/api/v4/projects/${CI_PROJECT_ID}/packages/generic/electron-builder/${CI_COMMIT_TAG}\"
-                       }
-                     ]
-                   }
-                 }" \
-                 "https://git.nosi.cv/api/v4/projects/${CI_PROJECT_ID}/releases"
+    - echo "Creating a new release on GitLab..."
+    - |
+      curl --request POST \
+           --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
+           --header "Content-Type: application/json" \
+           --data "{
+             \"name\": \"Release ${CI_COMMIT_TAG}\",
+             \"tag_name\": \"${CI_COMMIT_TAG}\",
+             \"description\": \"Release for commit ${CI_COMMIT_SHA}\",
+             \"assets\": {
+               \"links\": [
+                 {
+                   \"name\": \"Download\",
+                   \"url\": \"https://git.nosi.cv/api/v4/projects/${CI_PROJECT_ID}/packages/generic/electron-builder/${CI_COMMIT_TAG}\"
+                 }
+               ]
+             }
+           }" \
+           "https://git.nosi.cv/api/v4/projects/${CI_PROJECT_ID}/releases"
 
-    needs:
-        - build_packagedev
+  needs:
+    - build_packagedev
